# Generated by Django 3.1 on 2020-08-17 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qa', '0002_auto_20200811_2307'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=16)),
                ('email', models.EmailField(max_length=32)),
                ('password', models.CharField(max_length=32)),
            ],
        ),
        migrations.AlterField(
            model_name='answer',
            name='author',
            field=models.CharField(max_length=16),
        ),
        migrations.AlterField(
            model_name='question',
            name='author',
            field=models.CharField(max_length=16),
        ),
        migrations.AlterField(
            model_name='question',
            name='title',
            field=models.CharField(max_length=32),
        ),
    ]
